version: '3.8'

services:
  reverse-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: ./web
    expose:
      - "80"
      - "443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge