version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DEBUG=${DEBUG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  reverse-proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - web
      - backend